# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170201_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendgroup',
            name='friend_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FriendGroup', verbose_name='friend group'),
        ),
        migrations.AlterField(
            model_name='userfriendgroup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
    ]
