# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170201_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
